const Map<String, String> appStringsVi = {
  'appName': 'BabyCare Notes',
  'appTagline': 'Every Precious Moment Matters.',
  'splashLoading': 'Đang tải...',

  'navHome': 'Trang chủ',
  'navTips': 'Mẹo hay',
  'navLogs': 'Nhật ký',
  'navPair': 'Ghép nối',
  'navTimeline': 'Dòng thời gian',
  'navMore': 'Thêm',

  'pairSubtitle': 'Đồng bộ với người thân',
  'pairDesc': 'Quét mã QR để ghép nối với điện thoại của bạn đời hoặc người chăm sóc, cùng theo dõi em bé.',
  'pairScan': 'Quét mã ghép nối',
  'navShop': 'Cửa hàng',
  'navSettings': 'Cài đặt',

  'tabCubs': 'Em bé',
  'tabRoutines': 'Thói quen',
  'tabFamily': 'Gia đình',
  'tabJournals': 'Nhật ký',

  'addBaby': 'Thêm em bé',
  'editBaby': 'Sửa hồ sơ',
  'babyName': 'Tên em bé',
  'birthDate': 'Ngày sinh',
  'gender': 'Giới tính',
  'genderBoy': 'Bé trai',
  'genderGirl': 'Bé gái',
  'genderUnknown': 'Chưa rõ',
  'changePhoto': 'Đổi ảnh',
  'todaySummary': 'Hôm nay',
  'summaryFeeding': '{count} lần bú',
  'summarySleep': '{hours}h {mins}m ngủ',
  'summaryDiaper': '{count} lần tã',
  'summaryTotal': '{count} hoạt động',

  'feeding': 'Bú bình',
  'sleep': 'Ngủ',
  'pump': 'Hút sữa',
  'diaper': 'Tã',
  'height': 'Chiều cao',
  'vaccine': 'Tiêm',
  'milestones': 'Cột mốc',
  'growth': 'Tăng trưởng',
  'notebook': 'Ghi chú',
  'memories': 'Kỷ niệm',
  'timeline': 'Dòng thời gian',

  'feedingTitle': 'Ghi nhận bú',
  'feedingType': 'Loại sữa',
  'feedingBreast': 'Sữa mẹ',
  'feedingFormula': 'Sữa công thức',
  'feedingPump': 'Hút sữa',
  'amount': 'Lượng (ml)',
  'duration': 'Thời gian (phút)',
  'sleepTitle': 'Ghi nhận ngủ',
  'sleepStart': 'Giờ ngủ',
  'sleepEnd': 'Giờ thức',
  'sleepTotal': 'Tổng: {duration}',
  'diaperTitle': 'Thay tã',
  'diaperWet': 'Ướt',
  'diaperDirty': 'Bẩn',
  'diaperBoth': 'Cả hai',
  'growthTitle': 'Tăng trưởng',
  'weight': 'Cân nặng (kg)',
  'headCircumference': 'Vòng đầu (cm)',
  'growthChart': 'Biểu đồ tăng trưởng',
  'growthProLocked': 'Biểu đồ nâng cao bị khóa. Mở tại Cửa hàng.',
  'memoriesTitle': 'Kỷ niệm',
  'milestone': 'Cột mốc',
  'milestoneFirstSmile': 'Biết cười',
  'milestoneRollOver': 'Biết lẫy',
  'milestoneSitUp': 'Biết ngồi',
  'milestoneCrawl': 'Biết bò',
  'milestoneStand': 'Biết đứng',
  'milestoneWalk': 'Biết đi',
  'milestoneFirstWord': 'Biết nói',
  'milestoneOther': 'Khác',
  'vaccineTitle': 'Lịch tiêm',
  'vaccineReminder': 'Nhắc tiêm',
  'vaccineDue': 'Đến lịch tiêm',
  'vaccineDone': 'Đã tiêm',
  'vaccineReminderLocked': 'Nhắc tiêm bị khóa. Mở tại Cửa hàng.',
  'note': 'Ghi chú',
  'notes': 'Ghi chú',
  'save': 'Lưu',
  'cancel': 'Hủy',
  'delete': 'Xóa',
  'search': 'Tìm kiếm theo ngày...',
  'noLogs': 'Chưa có hoạt động nào',
  'addFirstLog': 'Ghi nhận hoạt động đầu tiên',
  'itsTime': 'Đến giờ rồi!',
  'multiBabyLocked': 'Thêm nhiều em bé bị khóa. Mở tại Cửa hàng.',

  'tipsTitle': 'Mẹo chăm sóc',
  'tip1Title': 'Giấc ngủ an toàn',
  'tip1Body': 'Đặt em bé ngủ ngửa trên nệm cứng, không gối, không chăn phủ mặt.',
  'tip2Title': 'Cho bú đúng cách',
  'tip2Body': 'Theo dõi thời gian và lượng bú giúp nhận biết nhu cầu dinh dưỡng.',
  'tip3Title': 'Theo dõi tã',
  'tip3Body': 'Thay tã thường xuyên giúp phòng tránh hăm và theo dõi sức khỏe.',
  'tip4Title': 'Tiêm chủng',
  'tip4Body': 'Tuân thủ lịch tiêm theo khuyến cáo y tế để bảo vệ em bé.',
  'tip5Title': 'Ghi lại cột mốc',
  'tip5Body': 'Lưu giữ khoảnh khắc đầu tiên — mỗi khoảnh khắc đều quý giá.',

  'onboardingTitle': 'Chào mừng đến BabyCare Notes',
  'onboardingSubtitle': 'Ghi lại mọi khoảnh khắc phát triển của em bé',
  'onboardingStep1': 'Theo dõi bú, ngủ, tã hằng ngày',
  'onboardingStep2': 'Biểu đồ tăng trưởng & lịch tiêm',
  'onboardingStep3': 'Lưu cột mốc và kỷ niệm đáng nhớ',
  'getStarted': 'Bắt đầu',
  'skip': 'Bỏ qua',
  'next': 'Tiếp',

  'shopTitle': 'Cửa hàng',
  'shopSubtitle': 'Kiếm sao hoặc mua để mở khóa theme & tính năng',
  'yourWallet': 'Ví sao của bạn',
  'coinsLabel': 'sao',
  'buyCoins': 'Mua sao',
  'buyCoinsDesc': 'Chọn gói để thêm sao',
  'yourCoins': 'Bạn có {count} sao',
  'processingPurchase': 'Đang xử lý giao dịch...',
  'billingUnavailable': 'Không thể thanh toán trên thiết bị này',
  'productsNotFound': 'Chưa có gói sao',
  'earnCoinsHint': 'Bạn cũng có thể nhận sao khi ghi hoạt động',
  'coinPack': 'Gói {num}',
  'coinAmount': '{count} sao',
  'earnCoins': 'Nhận sao',
  'dailyRewardDone': 'Đã nhận hôm nay',
  'earnStepDaily': 'Đăng nhập hằng ngày',
  'claimDailyButton': 'Nhận',
  'earnStepLogActivity': 'Ghi hoạt động',
  'earnStepLogActivityDesc': '+5 sao mỗi lần ghi',
  'earnStepMilestone': 'Ghi cột mốc',
  'earnStepMilestoneDesc': '+8 sao mỗi cột mốc',
  'earnStepStreak': 'Chuỗi ngày',
  'earnStepStreakDesc': '+15 sao khi duy trì',
  'earnStepBuy': 'Mua thêm sao',
  'buyWithGooglePlay': 'Google Play',
  'shopBrowse': 'Khám phá',
  'shopMenuAll': 'Tất cả',
  'shopMenuPremium': 'Premium',
  'shopMenuThemes': 'Theme',
  'shopMenuCards': 'Nền',
  'shopMenuSkins': 'Skin',
  'shopMenuFeatures': 'Tính năng',
  'shopEmptyCategory': 'Chưa có mục nào',
  'shopRemoveAds': 'Loại bỏ quảng cáo',
  'shopRemoveAdsDesc': 'Trải nghiệm không quảng cáo',
  'shopThemeBlossom': 'Hoa anh đào',
  'shopThemeBlossomDesc': 'Hồng pastel dịu dàng',
  'shopThemeMint': 'Bạc hà',
  'shopThemeMintDesc': 'Xanh mint tươi mát',
  'shopThemeLavender': 'Oải hương',
  'shopThemeLavenderDesc': 'Tím nhẹ nhàng',
  'shopThemeSunset': 'Hoàng hôn',
  'shopThemeSunsetDesc': 'Cam ấm áp',
  'shopBgClouds': 'Mây trắng',
  'shopBgCloudsDesc': 'Nền mây pastel',
  'shopBgStars': 'Đêm sao',
  'shopBgStarsDesc': 'Nền sao lấp lánh',
  'shopBgRainbow': 'Cầu vồng',
  'shopBgRainbowDesc': 'Nền cầu vồng',
  'shopBgBubbles': 'Bong bóng',
  'shopBgBubblesDesc': 'Nền bong bóng vui nhộn',
  'shopSkinSoft': 'Mềm mại',
  'shopSkinSoftDesc': 'Bo tròn mềm mại',
  'shopSkinCute': 'Dễ thương',
  'shopSkinCuteDesc': 'Viền hồng dễ thương',
  'shopSkinPlayful': 'Vui tươi',
  'shopSkinPlayfulDesc': 'Hiệu ứng kính mờ',
  'shopFeatMultiBaby': 'Nhiều em bé',
  'shopFeatMultiBabyDesc': 'Theo dõi nhiều em bé',
  'shopFeatExport': 'Xuất dữ liệu',
  'shopFeatExportDesc': 'Xuất nhật ký ra file',
  'shopFeatGrowthPro': 'Biểu đồ Pro',
  'shopFeatGrowthProDesc': 'Biểu đồ tăng trưởng nâng cao',
  'shopFeatVaccineReminder': 'Nhắc tiêm',
  'shopFeatVaccineReminderDesc': 'Thông báo lịch tiêm',
  'purchaseSuccess': 'Mua thành công!',
  'purchaseFailed': 'Mua thất bại',
  'insufficientCoins': 'Không đủ sao',
  'alreadyOwned': 'Đã sở hữu',
  'applied': 'Đã áp dụng',
  'apply': 'Áp dụng',
  'resetDefault': 'Mặc định',
  'resetToDefault': 'Đã về mặc định',
  'owned': 'Đã có',
  'active': 'Đang dùng',
  'removeAdsIap': 'Mua qua Google Play',
  'openingBilling': 'Đang mở thanh toán...',
  'coinsAdded': 'Đã thêm sao!',
  'removeAdsUnlocked': 'Đã loại bỏ quảng cáo!',
  'dailyRewardClaimed': 'Đã nhận thưởng hằng ngày!',
  'logActivityRewardEarned': '+5 sao từ ghi hoạt động!',
  'milestoneRewardEarned': '+8 sao từ cột mốc!',
  'streakRewardEarned': '+15 sao chuỗi ngày!',
  'configTimeout': 'Hết thời gian tải cấu hình. Dùng bản cache.',
  'configNetworkError': 'Lỗi mạng. Dùng bản cache.',

  'settings': 'Cài đặt',
  'language': 'Ngôn ngữ',
  'darkMode': 'Chế độ tối',
  'exportData': 'Xuất dữ liệu',
  'exportLocked': 'Xuất dữ liệu bị khóa. Mở tại Cửa hàng.',
  'privacyPolicy': 'Chính sách bảo mật',
  'about': 'Giới thiệu',
  'version': 'Phiên bản',
  'privacyPolicyBody': 'BabyCare Notes lưu dữ liệu em bé và cài đặt trên thiết bị. Chúng tôi không thu thập dữ liệu cá nhân trên máy chủ. Mua trong app qua Google Play. File JSON cấu hình IAP được tải từ api2.blwsmartware.net — không gửi dữ liệu cá nhân. Liên hệ: support@babycarenotes.app',
};
