const Map<String, String> appStringsEn = {
  'appName': 'BabyCare Notes',
  'appTagline': 'Every Precious Moment Matters.',
  'splashLoading': 'Loading...',

  'navHome': 'Home',
  'navTips': 'Tips',
  'navLogs': 'Logs',
  'navPair': 'Pair',
  'navTimeline': 'Timeline',
  'navMore': 'More',

  'pairSubtitle': 'Sync with family',
  'pairDesc': 'Scan a QR code to pair with your partner or caregiver and track baby together.',
  'pairScan': 'Scan pair code',
  'navShop': 'Shop',
  'navSettings': 'Settings',

  'tabCubs': 'Cubs',
  'tabRoutines': 'Routines',
  'tabFamily': 'Family',
  'tabJournals': 'Journals',

  'addBaby': 'Add baby',
  'editBaby': 'Edit profile',
  'babyName': 'Baby name',
  'birthDate': 'Birth date',
  'gender': 'Gender',
  'genderBoy': 'Boy',
  'genderGirl': 'Girl',
  'genderUnknown': 'Unknown',
  'changePhoto': 'Change photo',
  'todaySummary': 'Today',
  'summaryFeeding': '{count} feedings',
  'summarySleep': '{hours}h {mins}m sleep',
  'summaryDiaper': '{count} diapers',
  'summaryTotal': '{count} activities',

  'feeding': 'Bottle',
  'sleep': 'Sleep',
  'pump': 'Pump',
  'diaper': 'Diaper',
  'height': 'Height',
  'vaccine': 'Vaccine',
  'milestones': 'Milestones',
  'growth': 'Growth',
  'notebook': 'Notebook',
  'memories': 'Memories',
  'timeline': 'Timeline',

  'feedingTitle': 'Log feeding',
  'feedingType': 'Milk type',
  'feedingBreast': 'Breast milk',
  'feedingFormula': 'Formula',
  'feedingPump': 'Pumping',
  'amount': 'Amount (ml)',
  'duration': 'Duration (min)',
  'sleepTitle': 'Log sleep',
  'sleepStart': 'Sleep time',
  'sleepEnd': 'Wake time',
  'sleepTotal': 'Total: {duration}',
  'diaperTitle': 'Diaper change',
  'diaperWet': 'Wet',
  'diaperDirty': 'Dirty',
  'diaperBoth': 'Both',
  'growthTitle': 'Growth',
  'weight': 'Weight (kg)',
  'headCircumference': 'Head (cm)',
  'growthChart': 'Growth chart',
  'growthProLocked': 'Advanced charts locked. Unlock in Shop.',
  'memoriesTitle': 'Memories',
  'milestone': 'Milestone',
  'milestoneFirstSmile': 'First smile',
  'milestoneRollOver': 'Roll over',
  'milestoneSitUp': 'Sit up',
  'milestoneCrawl': 'Crawl',
  'milestoneStand': 'Stand',
  'milestoneWalk': 'Walk',
  'milestoneFirstWord': 'First word',
  'milestoneOther': 'Other',
  'vaccineTitle': 'Vaccine schedule',
  'vaccineReminder': 'Vaccine reminder',
  'vaccineDue': 'Due for vaccine',
  'vaccineDone': 'Completed',
  'vaccineReminderLocked': 'Vaccine reminders locked. Unlock in Shop.',
  'note': 'Note',
  'notes': 'Notes',
  'save': 'Save',
  'cancel': 'Cancel',
  'delete': 'Delete',
  'search': 'Search by date...',
  'noLogs': 'No activities yet',
  'addFirstLog': 'Log your first activity',
  'itsTime': "It's time!",
  'multiBabyLocked': 'Multiple babies locked. Unlock in Shop.',

  'tipsTitle': 'Parenting tips',
  'tip1Title': 'Safe sleep',
  'tip1Body': 'Place baby on their back on a firm mattress, no pillows or blankets over face.',
  'tip2Title': 'Feeding tracking',
  'tip2Body': 'Track feeding times and amounts to understand nutrition needs.',
  'tip3Title': 'Diaper care',
  'tip3Body': 'Change diapers regularly to prevent rash and monitor health.',
  'tip4Title': 'Vaccinations',
  'tip4Body': 'Follow the recommended vaccine schedule to protect your baby.',
  'tip5Title': 'Record milestones',
  'tip5Body': 'Save first moments — every precious moment matters.',

  'onboardingTitle': 'Welcome to BabyCare Notes',
  'onboardingSubtitle': 'Track every precious moment of your baby\'s growth',
  'onboardingStep1': 'Track feeding, sleep & diapers daily',
  'onboardingStep2': 'Growth charts & vaccine schedule',
  'onboardingStep3': 'Save milestones and memories',
  'getStarted': 'Get started',
  'skip': 'Skip',
  'next': 'Next',

  'shopTitle': 'Shop',
  'shopSubtitle': 'Earn or buy stars to unlock themes & features',
  'yourWallet': 'Your star wallet',
  'coinsLabel': 'stars',
  'buyCoins': 'Buy stars',
  'earnCoins': 'Earn stars',
  'dailyRewardDone': 'Claimed today',
  'earnStepDaily': 'Daily login',
  'claimDailyButton': 'Claim',
  'earnStepLogActivity': 'Log activity',
  'earnStepLogActivityDesc': '+5 stars per log',
  'earnStepMilestone': 'Record milestone',
  'earnStepMilestoneDesc': '+8 stars per milestone',
  'earnStepStreak': 'Day streak',
  'earnStepStreakDesc': '+15 stars for streak',
  'earnStepBuy': 'Buy more stars',
  'buyWithGooglePlay': 'Google Play',
  'shopBrowse': 'Browse',
  'shopMenuAll': 'All',
  'shopMenuPremium': 'Premium',
  'shopMenuThemes': 'Themes',
  'shopMenuCards': 'Backgrounds',
  'shopMenuSkins': 'Skins',
  'shopMenuFeatures': 'Features',
  'shopEmptyCategory': 'Nothing here yet',
  'shopRemoveAds': 'Remove ads',
  'shopRemoveAdsDesc': 'Ad-free experience',
  'shopThemeBlossom': 'Blossom',
  'shopThemeBlossomDesc': 'Soft pastel pink',
  'shopThemeMint': 'Mint',
  'shopThemeMintDesc': 'Fresh mint green',
  'shopThemeLavender': 'Lavender',
  'shopThemeLavenderDesc': 'Gentle purple',
  'shopThemeSunset': 'Sunset',
  'shopThemeSunsetDesc': 'Warm orange glow',
  'shopBgClouds': 'Clouds',
  'shopBgCloudsDesc': 'Pastel cloud background',
  'shopBgStars': 'Starry night',
  'shopBgStarsDesc': 'Sparkling stars',
  'shopBgRainbow': 'Rainbow',
  'shopBgRainbowDesc': 'Rainbow gradient',
  'shopBgBubbles': 'Bubbles',
  'shopBgBubblesDesc': 'Playful bubbles',
  'shopSkinSoft': 'Soft',
  'shopSkinSoftDesc': 'Extra rounded corners',
  'shopSkinCute': 'Cute',
  'shopSkinCuteDesc': 'Pink border style',
  'shopSkinPlayful': 'Playful',
  'shopSkinPlayfulDesc': 'Glass effect cards',
  'shopFeatMultiBaby': 'Multi-baby',
  'shopFeatMultiBabyDesc': 'Track multiple babies',
  'shopFeatExport': 'Export data',
  'shopFeatExportDesc': 'Export logs to file',
  'shopFeatGrowthPro': 'Growth Pro',
  'shopFeatGrowthProDesc': 'Advanced growth charts',
  'shopFeatVaccineReminder': 'Vaccine reminders',
  'shopFeatVaccineReminderDesc': 'Push notification reminders',
  'purchaseSuccess': 'Purchase successful!',
  'purchaseFailed': 'Purchase failed',
  'insufficientCoins': 'Not enough stars',
  'alreadyOwned': 'Already owned',
  'applied': 'Applied',
  'apply': 'Apply',
  'resetDefault': 'Default',
  'resetToDefault': 'Reset to default',
  'owned': 'Owned',
  'active': 'Active',
  'removeAdsIap': 'Buy via Google Play',
  'openingBilling': 'Opening billing...',
  'coinsAdded': 'Stars added!',
  'removeAdsUnlocked': 'Ads removed!',
  'dailyRewardClaimed': 'Daily reward claimed!',
  'logActivityRewardEarned': '+5 stars for logging!',
  'milestoneRewardEarned': '+8 stars for milestone!',
  'streakRewardEarned': '+15 stars for streak!',
  'configTimeout': 'Config timeout. Using cached version.',
  'configNetworkError': 'Network error. Using cached version.',

  'settings': 'Settings',
  'language': 'Language',
  'darkMode': 'Dark mode',
  'exportData': 'Export data',
  'exportLocked': 'Export locked. Unlock in Shop.',
  'privacyPolicy': 'Privacy policy',
  'about': 'About',
  'version': 'Version',
  'privacyPolicyBody': 'BabyCare Notes stores baby data and settings locally on your device. We do not collect personal data on our servers. In-app purchases are processed by Google Play. A remote config JSON is fetched from api2.blwsmartware.net to manage IAP availability — no personal data is sent. Contact: support@babycarenotes.app',
};
